name = "Wakpack"
author = "Wak Comp. team"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1d891a93769bcc0481a6ed38a2b24fe0fe2f7d3c9366c42e2ac81a7522d4ebd1"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"

[options]
datapack-folder = "kubejs/data"
