name = "Wakpack"
author = "Wak Comp. team"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "850edbe17f42d7e30430c5e1482bc84950e1988a6ea0370d6a3efb971ebdd6b4"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"
