name = "Wakpack"
author = "Wak Comp. team"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b9ea7be65c8a39616e0889cd796405bf62461435096b9a299d0071d9f2eb125b"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"
