name = "Wakpack"
author = "Wak Comp. team"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "654ef09737f539bf9a0f1c6e9c4a67cd0e972d71f715834612ac144d2b14fc9f"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"

[options]
datapack-folder = "config/openloader/data"
