name = "Wakpack"
author = "Wak Comp. team"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "07e8fddcb9ca77254bfd3b1fabd8b66136461420eba36159168688a78dba03d0"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"
