name = "Wakpack"
author = "Wak Comp. team"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9c545428aa7dd10dac2145bde5d5d8a60e758cb517ca6a7bc066c9fccb3fdf95"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"
