name = "Wakpack"
author = "Wak Comp. team"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ec545550089f621cb4cad6cfaf3e95f9ffd62c21cb106b6b39cda1626c998035"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"
