name = "Wakpack"
author = "Wak Comp. team"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e496b2dc9840d0289a82a0b5de04244e20ad44abc0768275c22d6d30a818461b"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"

[options]
datapack-folder = "kubejs/data"
