name = "Wakpack"
author = "Wak Comp. team"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c7982f508bc60e2b47bcad42cdb67e9096fc92651190f27404002d38a53e86d8"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"
