name = "Wakpack"
author = "Wak Comp. team"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0b7e4f333f31db9130d0f7169c574683d01c617415bcdb965808d1f5e2a799b8"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"
