name = "Wakpack"
author = "Wak Comp. team"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ef5930e68b6e5ab0eba74441167ef50dcf600714e94eb909fc8c993dc1179905"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"

[options]
datapack-folder = "kubejs/data"
