name = "Wakpack"
author = "Wak Comp. team"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "679ebb71b03ec6a193fdb41c08924c81a885684e6dd31f8210b840ae4bdac805"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"

[options]
datapack-folder = "config/openloader/data"
