name = "Wakpack"
author = "Wak Comp. team"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fe7d7e5d3df666f8496827c191c80504b4cca78518d24ba60924b9810797dd32"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"

[options]
datapack-folder = "config/openloader/data"
