name = "Wakpack"
author = "Wak Comp. team"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7cb746cb85e6696724a809fdbc98b2c7a339e8929d275f93519a9aa82e9d591d"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"

[options]
datapack-folder = "kubejs/data"
