name = "Wakpack"
author = "Wak Comp. team"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "70ae7c362ec93311af60a105e9b8ab8164e10bd090de775647106a687a3b292b"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"

[options]
datapack-folder = "config/openloader/data"
