name = "Wakpack"
author = "Wak Comp. team"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5c20e5f2a60f638fdd6a846254e190d7775dc468b2bd94f55d25a1251ec8834c"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"
