name = "Wakpack"
author = "Wak Comp. team"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c9e2ea5f814c19f534f74dfddc6d4f699c3f780c6ba97b3c0a085c27e2fe232f"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"

[options]
datapack-folder = "config/openloader/data"
