name = "Wakpack"
author = "Wak Comp. team"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7a326fd4ef88cc94f8362e61ce15c2fcb865592ad886e19958c93a77feda8f03"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"
